#!/bin/bash

MIR_SERVER_PLATFORM_PATH=/apps/mir-server.sideload/current/usr/lib/x86_64-linux-gnu/mir/server-platform LD_LIBRARY_PATH=/apps/mir-server.sideload/current/usr/lib/x86_64-linux-gnu/:/apps/mir-server.sideload/current/usr/lib/x86_64-linux-gnu/mesa-egl/ /apps/mir-server.sideload/current/bin/mir-server --vt 1 --file /run/mir_socket
